347project/347project/learningproject/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.CourseList.as_view(), name='courses'),
    path('publish/', views.PublishCourse.as_view(), name='publish'),
    path('course_details/<slug:slug>/', views.course_details, name='course_details'),
    path('course_details/update/<slug:slug>/', views.CourseUpdateView.as_view(), name='course_update'),
    path('course_details/delete/<slug:slug>/', views.CourseDeleteView.as_view(), name='course_delete'),
    path('my_courses/', views.MyCourses.as_view(), name='my_courses'),
    path('question/<pk>/', views.question, name='question'),
]

347project/347project/learningproject/learningproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings
from users.admin import subadmin_site


urlpatterns = [
    path('admin/', admin.site.urls),
    path('subadmin/', subadmin_site.urls),
    path('', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('vlogs/', include('vlogs.urls')),
    path('courses/', include('courses.urls')),
    path('a2zStore/', include('a2zStore.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

347project/347project/learningproject/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile_update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('terms_conditions/', views.TermsConditions.as_view(), name='terms_conditions'),
    path('privacy/', views.Privacy.as_view(), name='privacy'),
    path('help/', views.HelpView.as_view(), name='help'),
    path('help/helpdescribe/', views.HelpDescribe.as_view(), name='help_describe'),
    path('contact/', views.contact, name='contact_us'),


]

347project/347project/learningproject/courses/models.py
from django.db import models
from embed_video.fields import EmbedVideoField
from django.contrib.auth.models import User
from django.utils.text import slugify
import uuid
from django.urls import reverse

# Create your models here.


class Course(models.Model):
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='course_teacher')
    course_title = models.CharField(max_length=255)
    course_poster = models.ImageField(verbose_name='Upload a course poster', default='default2.jpg', upload_to='course_posters/', null=True, blank=True)
    video = EmbedVideoField(null=True, blank=False)
    course_article = models.TextField(verbose_name='Course Article')
    slug = models.SlugField(max_length=255, unique=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.course_title

    def get_absolute_url(self):
        return reverse('course_details')

    def save(self):
        self.slug = slugify(self.course_title + '-' + str(uuid.uuid4()))
        super(Course, self).save()


class Question(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='course_question')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='student_question')
    question = models.TextField()
    question_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-question_date']

    def __str__(self):
        return self.question


class Reply(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='q_reply')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_reply')
    reply = models.TextField()
    reply_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.reply

347project/347project/learningproject/courses/forms.py
from django import forms
from .models import Reply, Question


class QuestionForm(forms.ModelForm):
    question = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Say Something...'
        })
    )

    class Meta:
        model = Question
        fields = ['question']


class ReplyForm(forms.ModelForm):
    reply = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Say Something...'
        })
    )

    class Meta:
        model = Reply
        fields = ['reply']

347project/347project/learningproject/courses/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, ListView, TemplateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse, reverse_lazy
import uuid
from django.utils.text import slugify
from .models import Course, Question, Reply
from .forms import QuestionForm, ReplyForm
from django.contrib import messages
from django.db.models import Q

# Create your views here.


class CourseList(ListView):
    context_object_name = 'course_list'
    model = Course
    template_name = 'courses/course_list.html'
    paginate_by = 6

    def get_queryset(self):
        filter_val = self.request.GET.get("filter", "")
        order_by = self.request.GET.get("orderby", "id")
        if filter_val != "":
            cat = Course.objects.filter(
                Q(course_title__contains=filter_val) | Q(course_article__contains=filter_val)).order_by(order_by)
        else:
            cat = Course.objects.all().order_by(order_by)

        return cat

    def get_context_data(self, **kwargs):
        context = super(CourseList, self).get_context_data(**kwargs)
        context["filter"] = self.request.GET.get("filter", "")
        context["orderby"] = self.request.GET.get("orderby", "id")
        context["all_table_fields"] = Course._meta.get_fields()
        return context


class PublishCourse(LoginRequiredMixin, CreateView):
    model = Course
    template_name = 'courses/publish_course.html'
    fields = ('course_title', 'course_poster', 'video', 'course_article')

    def form_valid(self, form):
        course_obj = form.save(commit=False)
        course_obj.teacher = self.request.user
        title = course_obj.course_title
        course_obj.slug = slugify(title.replace(" ", "-") + str(uuid.uuid4()))
        course_obj.save()
        return HttpResponseRedirect(reverse('courses:courses'))


@login_required
def course_details(request, slug):
    course = Course.objects.get(slug=slug)
    form = QuestionForm()
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.user = request.user
            question.course = course
            question.save()
            return HttpResponseRedirect(reverse('courses:course_details', kwargs={'slug': slug}))

    return render(request, 'courses/course_details.html', {'course': course, 'form': form})


class CourseUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Course
    template_name = 'courses/course-update.html'
    fields = ('course_title', 'course_poster', 'video', 'course_article')

    def form_valid(self, form):
        course_obj = form.save(commit=False)
        course_obj.teacher = self.request.user
        title = course_obj.course_title
        course_obj.slug = slugify(title.replace(" ", "-") + str(uuid.uuid4()))
        course_obj.save()
        return HttpResponseRedirect(reverse('courses:course_details', kwargs={'slug': course_obj.slug}))

    def test_func(self):
        course = self.get_object()
        return self.request.user == course.teacher


class CourseDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Course
    template_name = 'courses/course-delete.html'
    success_url = reverse_lazy('courses:courses')

    def test_func(self):
        course = self.get_object()
        return self.request.user == course.teacher


class MyCourses(LoginRequiredMixin, ListView):
    context_object_name = 'course_list'
    model = Course
    template_name = 'courses/my_courses.html'

    def test_func(self):
        course = self.get_object()
        return self.request.user == course.teacher


@login_required
def question(request, pk):
    form = ReplyForm()
    question = Question.objects.get(pk=pk)
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.question = question
            reply.save()
            return HttpResponseRedirect(reverse('courses:question', kwargs={'pk': pk}))
    return render(request, 'courses/question.html', {'form': form, 'question': question})

347project/347project/learningproject/templates/courses/course-delete.html
{% extends 'users/base.html' %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
        </div>
        <a href="{% url 'courses:course_details' course.slug %}">< Back</a>
    </div>
</div>


    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12 border-bottom">
            <form method = "POST">
                {% csrf_token %}
                <h3>Are you sure?</h3>
                <p>You are about to delete this post and this can not be undone</p>
                <div class="d-grid gap-2">
                    <button class="btn btn-danger mt-3">Delete</button>
                </div>
            </form>
            <br>
        </div>
    </div>
</div>
{% endblock content %}

347project/347project/learningproject/templates/courses/course-update.html
{% extends 'users/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->

        <!-- Main Content Here -->
        <div class="card o-hidden border-0 shadow-lg ">
          <div class="card-body p-0">
            <div class="row">
              <div class="col-lg-3"></div>
              <div class="col-lg-6">
                <div class="p-5">
                    <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Update Your Course!</h1>
                  </div>


                  </div>

                  <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form | crispy}}
                        <button type="submit" class="site-btn btn-success btn-block">Save</button>
                  </form>
                  <hr>

                </div>
              </div>
            </div>
          </div>
        </div>



    </div>
    <!-- /.container-fluid -->
{% endblock content %}

347project/347project/learningproject/templates/courses/course_details.html
{% extends 'users/base.html' %}
{% load embed_video_tags %}
{% load crispy_forms_tags %}
{% load static %}
{% block title_block %} {{course.course_title}} {% endblock %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
        </div>
        <a href="{% url 'courses:courses' %}">< Back</a>
    </div>
</div>

<div class="container">
    <h2 class="text-center p-5 border-bottom"><strong>{{course.course_title}}</strong>
        {% if request.user == course.teacher %}
        <a href="{% url 'courses:course_update' course.slug %}" style="color: #333;"><small><i class="far fa-edit"></i></small></a>
        <a href="{% url 'courses:course_delete' course.slug %}" style="color: #333;"><small><i class="fas fa-trash"></i></small></a>
        {% endif%}
    </h2>
    <div class="row border-bottom">
        <div class="col-sm-8">
            <strong>Instructor: </strong>{{course.teacher}} <br>
            <strong>Published on: </strong>{{course.publish_date}} <br>
            <strong>Update on: </strong>{{course.update_date}} <br><br><br>
        </div>
        <!--div class="col">
            <img src="/media/{{course.course_poster}}" alt="course_poster" width="80%" height="300px">
            <br><br>
        </div-->

        <div class="text-center">
            {% video course.video '900x500' %}
        </div>

        <p>{{course.course_article|linebreaks}}</p><br>
    </div>
</div>
<!--h3>Practice quiz</h3>
<iframe src="{{course.quiz_url}}" frameborder="0" width="500px" height="1000px"></iframe-->

<hr>
<div class="container">
    Questions | {{course.course_question.count}}
    <div class="row">
        <div class="col-sm-6">
            <h5>Questions</h5>
            {% for question in course.course_question.all %}
            <p>
                @{{question.user}} <br>
                <a href="{% url 'courses:question' pk=question.pk %}">{{question}}</a>
            </p>
            {% endfor %}
        </div>
        {% if not perms.courses.add_course %}
        <div class="col-sm-6">
            <form action="" method="POST">
                {{form|crispy}}
                {% csrf_token %}

                <button type="submit" class="btn btn-info btn-sm">Ask</button>
                <br><br>
            </form>
        </div>
        {% endif %}
    </div>
</div>

{% endblock content %}

347project/347project/learningproject/templates/courses/course_list.html
{% extends 'users/base.html' %}
{% block title_block %} Home {% endblock %}
{% block content %}
<div class="container" xmlns="http://www.w3.org/1999/html">
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
        </div>
        <a href="{% url 'home' %}">< Back</a>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="search-element">
                <form method="get">
                    <button class="btn btn-primary" type="submit" style="float:right"><i class="fas fa-search"></i>
                    </button>
                    <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250"
                           style="width: 250px;float:right" name="filter" value="{{filter}}">
                </form>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="search-element">
                <b>Sort by: </b>

                <a href="{% url 'courses:courses' %}?filter={{ filter }}&orderby=course_title">Title</a> |
                <a href="{% url 'courses:courses' %}?filter={{ filter }}&orderby=course_article">Article</a>
            </div>
        </div>
    </div>

</div>
<div class="container">
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <h2>Choose your desire course!</h2>
        </div>
    </div>
</div>
<br>
<br>


<div class="mx-5">

    <div class="row d-flex justify-content-center">

        {% for course in course_list %}
        <div class="card o-hidden border-0 shadow-lg my-4 col-lg-3 ">
            <div class="card-body">
                <img class="card-img-top rounded float-right" src="/media/{{course.course_poster}}"
                     alt="course_image" width="300px" height="200px">
                <div class="card-body text-center">
                    <!--div class="row justify-content">
                        <div class="col-md-5  border-bottom position-relative c"-->

                    <h4>
                        <a href="{% url 'courses:course_details' slug=course.slug %}">{{course.course_title}}</a>
                        {% if request.user == course.teacher %}
                        <small class="text-muted ">
                            <a href="{% url 'courses:course_update' course.slug %}"><small><i
                                    class="far fa-edit"></i></small></a>
                            <a href="{% url 'courses:course_delete' course.slug %}"><small><i
                                    class="fas fa-trash"></i></small></a>
                        </small>
                        {% endif%}
                    </h4>
                    <small class="text-muted">Instructor: {{course.teacher}} </small><br>
                    <small class="text-muted">Published on: {{course.publish_date}}</small>

                </div>
            </div>
        </div>
        &nbsp &nbsp &nbsp
        {% endfor %}
    </div>
</div>
<div class="container">
    <hr>
</div>

<div class="row">
<div class="col-lg-12">
<div class="card">

                  <div class="card-body">
                    <nav aria-label="Page navigation example">
                      <ul class="pagination justify-content-center mt-3">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="{% url 'courses:courses' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.previous_page_number }}">Previous</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                        {% endif %}
                        {% for i in paginator.page_range %}
                                <li class="page-item {% if i == page_obj.number %}active{% endif %}"><a class="page-link" href="{% url 'courses:courses' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="{% url 'courses:courses' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.next_page_number }}">Next</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        {% endif %}

                      </ul>
                    </nav>
                  </div>
                </div>
                </div>
</div>


{% endblock content %}

347project/347project/learningproject/templates/courses/my_courses.html
{% extends 'users/base.html' %}
{% block title_block %} Your courses {% endblock %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
        </div>
        <a href="{% url 'home' %}">< Back</a>
    </div>

</div>
<div class="container">
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <h2 class="text-center">My courses</h2>
        </div>
    </div>
</div>
<br>
<br>

<div class="mx-5">

    <div class="row d-flex justify-content-center">
{% for course in course_list %}
{% if user == course.teacher %}
        <div class="card o-hidden border-0 shadow-lg my-4 col-lg-3 ">
            <div class="card-body">
        <img src="/media/{{course.course_poster}}" alt="course_image" width="300px" height="200px" class="card-img-top rounded float-right">
                <div class="card-body text-center">
                <h4>
        <a href="{% url 'courses:course_details' slug=course.slug %}">{{course.course_title}}</a>
        {% if request.user == course.teacher %}
            <small class="text-muted ">
        <a href="{% url 'courses:course_update' course.slug %}" ><small><i class="far fa-edit"></i></small></a>
        <a href="{% url 'courses:course_delete' course.slug %}" ><small><i class="fas fa-trash"></i></small></a>
                </small>
        {% endif%}
        </h4>
        <small class="text-muted">Instructor: @{{course.teacher}}</small>&nbsp;<br>
        <small class="text-muted">Published on: {{course.publish_date}}</small>
    </div>
</div>
        </div>
         &nbsp &nbsp &nbsp
{% endif %}
{% endfor %}
        </div>
</div>

<div class="container">
    <hr>
</div>

<div class="row">
<div class="col-lg-12">
<div class="card">

                  <div class="card-body">
                    <nav aria-label="Page navigation example">
                      <ul class="pagination justify-content-center mt-3">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="{% url 'courses:courses' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.previous_page_number }}">Previous</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                        {% endif %}
                        {% for i in paginator.page_range %}
                                <li class="page-item {% if i == page_obj.number %}active{% endif %}"><a class="page-link" href="{% url 'courses:courses' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="{% url 'courses:courses' %}?filter={{ filter }}&orderby={{ orderby }}&page={{ page_obj.next_page_number }}">Next</a></li>
                        {% else %}
                            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                        {% endif %}

                      </ul>
                    </nav>
                  </div>
                </div>
                </div>
</div>
{% endblock content %}

347project/347project/learningproject/templates/courses/publish_course.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Create a course {% endblock %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
        </div>
        <a href="{% url 'home' %}">< Back</a>
    </div>
</div>
<div class="container">
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <h2 class="text-center">Create your course here</h2>
        </div>
    </div>
    <form action="" method="POST" enctype="multipart/form-data">
        {{form|crispy}}
        {% csrf_token %}
        <br>
        <button type="submit" class="btn btn-success btn-sm">Publish</button>
    </form>

</div>

{% endblock content %}

347project/347project/learningproject/templates/courses/question.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{question}} {% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <h2 class="text-center">Support Forum</h2>
        </div>
    </div>


    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12 ">
            <h3>Q: {{question}} </h3>
            {% if perms.courses.add_course %}
            <form action="" method="POST">
                {{form|crispy}}
                {% csrf_token %}
                <div class="d-grid gap-2">
                    <button class="btn btn-success mt-3">Submit</button>
                </div>

            </form>
            {% endif %}
            <br>


            {{question.q_reply.count}} replied


            <h5>Replies</h5>
            {% for reply in question.q_reply.all %}
            <p>
                @{{reply.user}} <br>
                {{reply}}
            </p>
            {% endfor %}


        </div>

    </div>
</div>
    {% endblock content %}