347project/347project/learningproject/a2zStore/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="store"),
    path("products/<int:myid>", views.product, name="Product"),
    path("checkout/", views.checkout, name="Checkout"),
    path("tracker/", views.tracker, name="Tracker"),
]

347project/347project/learningproject/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.CourseList.as_view(), name='courses'),
    path('publish/', views.PublishCourse.as_view(), name='publish'),
    path('course_details/<slug:slug>/', views.course_details, name='course_details'),
    path('course_details/update/<slug:slug>/', views.CourseUpdateView.as_view(), name='course_update'),
    path('course_details/delete/<slug:slug>/', views.CourseDeleteView.as_view(), name='course_delete'),
    path('my_courses/', views.MyCourses.as_view(), name='my_courses'),
    path('question/<pk>/', views.question, name='question'),
]

347project/347project/learningproject/learningproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings
from users.admin import subadmin_site


urlpatterns = [
    path('admin/', admin.site.urls),
    path('subadmin/', subadmin_site.urls),
    path('', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('vlogs/', include('vlogs.urls')),
    path('courses/', include('courses.urls')),
    path('a2zStore/', include('a2zStore.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

347project/347project/learningproject/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile_update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('terms_conditions/', views.TermsConditions.as_view(), name='terms_conditions'),
    path('privacy/', views.Privacy.as_view(), name='privacy'),
    path('help/', views.HelpView.as_view(), name='help'),
    path('help/helpdescribe/', views.HelpDescribe.as_view(), name='help_describe'),
    path('contact/', views.contact, name='contact_us'),


]

347project/347project/learningproject/a2zStore/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    product_id = models.AutoField
    product_name = models.CharField(max_length=50, null=False, blank=False)
    category = models.CharField(max_length=50, default="", null=False, blank=False)
    price = models.IntegerField(null=False, blank=False)
    desc = models.TextField(max_length=800,blank=True)
    book_url = models.URLField(verbose_name='Book link', default="",null=False, blank=False)
    pub_date = models.DateField()
    image = models.ImageField(upload_to="book_images/", default="", null=False, blank=False)

    def __str__(self):
        return self.product_name


class Orders(models.Model):
    order_id = models.AutoField(primary_key=True)
    items_json = models.CharField(max_length=5000)
    name = models.CharField(max_length=90, null=False, blank=False)
    email = models.CharField(max_length=111)
    address = models.CharField(max_length=111, null=False, blank=False)
    city = models.CharField(max_length=111, null=False, blank=False)
    state = models.CharField(max_length=111, null=False, blank=False)
    zip_code = models.CharField(max_length=111, null=False, blank=False)
    phone = models.CharField(max_length=111, null=False, blank=False)


class OrderUpdate(models.Model):
    update_id = models.AutoField(primary_key=True)
    order_id = models.IntegerField(default="")
    update_desc = models.CharField(max_length=5000)
    timestamp = models.DateField(auto_now_add= True)

    def __str__(self):
        return self.update_desc[0:7] + "..."

347project/347project/learningproject/courses/models.py
from django.db import models
from embed_video.fields import EmbedVideoField
from django.contrib.auth.models import User
from django.utils.text import slugify
import uuid
from django.urls import reverse

# Create your models here.


class Course(models.Model):
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='course_teacher')
    course_title = models.CharField(max_length=255)
    course_poster = models.ImageField(verbose_name='Upload a course poster', default='default2.jpg', upload_to='course_posters/', null=True, blank=True)
    video = EmbedVideoField(null=True, blank=False)
    course_article = models.TextField(verbose_name='Course Article')
    slug = models.SlugField(max_length=255, unique=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.course_title

    def get_absolute_url(self):
        return reverse('course_details')

    def save(self):
        self.slug = slugify(self.course_title + '-' + str(uuid.uuid4()))
        super(Course, self).save()


class Question(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='course_question')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='student_question')
    question = models.TextField()
    question_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-question_date']

    def __str__(self):
        return self.question


class Reply(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='q_reply')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_reply')
    reply = models.TextField()
    reply_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.reply

347project/347project/learningproject/a2zStore/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product, Orders, OrderUpdate
from math import ceil
import json
from django.contrib import messages
# Create your views here.


def index(request):
    allProds =[]
    catprods = Product.objects.values('category', 'id')
    cats = {item['category'] for item in catprods}
    for cat in cats:
        prod = Product.objects.filter(category=cat)
        n = len(prod)
        nSlides = n // 4 + ceil((n / 4) - (n // 4))
        allProds.append([prod, range(1, nSlides), nSlides])
    params = {'allProds': allProds}
    return render(request, 'a2zStore/index.html', params)


def product(request, myid):
    # Fetch the using the id
    product = Product.objects.filter(id = myid)
    return render (request, 'a2zStore/prodView.html', {'product': product[0]})


def checkout(request):
    if request.method == "POST":
        items_json = request.POST.get('itemsJson', '')
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        address = request.POST.get('address1', '') + " " + request.POST.get('address2', '')
        city = request.POST.get('city', '')
        state = request.POST.get('state', '')
        zip_code = request.POST.get('zip_code', '')
        phone = request.POST.get('phone', '')
        if name == '' or email == '' or address == '' or city == '' or state == '' or zip_code == '' or len(phone) < 11:
            messages.error(request, "Please fill the form correctly")
        else:
            order = Orders(items_json=items_json, name=name, email=email, address=address, city=city, state=state, zip_code=zip_code, phone=phone)
            order.save()
            update = OrderUpdate(order_id=order.order_id, update_desc="The order has been placed")
            update.save()
            thank = True
            id = order.order_id
            return render(request, 'a2zStore/checkout.html', {'thank': thank, 'id': id})
    return render(request, 'a2zStore/checkout.html')


def tracker(request):
    if request.method=="POST":
        orderId = request.POST.get('orderId', '')
        email = request.POST.get('email', '')
        try:
            order = Orders.objects.filter(order_id=orderId, email=email)
            if len(order)>0:
                update = OrderUpdate.objects.filter(order_id=orderId)
                updates = []
                for item in update:
                    updates.append({'text': item.update_desc, 'time': item.timestamp})
                    response = json.dumps([updates, order[0].items_json], default=str)
                return HttpResponse(response)
            else:
                return HttpResponse('{}')
        except Exception as e:
            return HttpResponse('{}')

    return render(request, 'a2zStore/tracker.html')

347project/347project/learningproject/a2zStore/templates/a2zStore/basic.html
<!doctype html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">


    <!--Font Link-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Open+Sans:wght@800&display=swap"
          rel="stylesheet">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="{% static 'webuni/css/bootstrap.min.css'%}"/>
    <link rel="stylesheet" href="{% static 'webuni/css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'webuni/css/owl.carousel.css' %}"/>
    <link rel="stylesheet" href="{% static 'webuni/css/style.css'%}"/>
    <link rel="stylesheet" href="{% static 'webuni/css/freelancer.css'%}"/>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css"/>

    <style>
      {% block css %} {% endblock %}





    </style>
</head>

<body id="bg">
<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}"><img class="logo"
                                                             src="{% static 'users/images/smalllogo-01.png'%}"
                                                             alt=""></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup ">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>

                {% if user.is_authenticated %}
                {% if perms.courses.add_course %}
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="buton" aria-expanded="false">Courses</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'courses:publish' %}">Add Course</a></li>
                        <li><a class=" dropdown-item" href="{% url 'courses:my_courses' %}">My Courses</a></li>
                        <li><a class="dropdown-item" href="{% url 'courses:courses' %}">All courses</a></li>
                    </ul>
                </div>
                {% else%}
                <a class="nav-link" href="{% url 'courses:courses' %}">Courses</a>
                {% endif %}
                <a class="nav-link" href="{% url 'store' %}">Store</a>
                <a class="nav-link" href="{% url 'post_list' %}">Vlogs</a>
                <a class="nav-link" href="{% url 'Tracker' %}">Tracker</a>


                {% else %}

                <a class="nav-link" href="{% url 'account_login' %}">Courses</a>
                <a class="nav-link" href="{% url 'account_login' %}">Store</a>
                <a class="nav-link" href="{% url 'account_login' %}">Vlogs</a>
                <a class="nav-link" href="{% url 'account_login' %}">Tracker</a>

                {% endif %}


        <div>
        <form class="d-flex" id="authstyle">
            {% if user.is_authenticated %}
            <div class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" role="button"
                   aria-expanded="false"><i class="fas fa-user"></i></a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
                </ul>
            </div>
            {% else %}
            <a href="{% url 'account_signup' %}" class="btn "
               style="color: white; background-color: #fd5e14; margin-left: 500px;" type="submit"
               id=" header-links"> Create Account </a>
            <a href="{% url 'account_login' %}" class="btn "
               style="color: white; background-color: #fd5e14; margin-left: 10px; " type="submit"
               id=" header-links">Log In</a>
            {% endif %}
        </form>
        </div>
                </div>
        </div>
        {% if user.is_authenticated %}

        <button type="button" class="btn btn-secondary mx-2" id="popcart"
                data-container="body" data-toggle="popover" data-placement="bottom" data-html="true"
                data-content="Vivamus
              sagittis lacus vel augue laoreet rutrum faucibus.">
            Cart(<span id="cart">0 </span>)
        </button>
        {% endif %}
    </div>
    </div>
    </div>
</nav>

<!-- Hero section end -->
<div>
    <div class="container">

        {% for message in messages %}

        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}

    </div>
</div>
{% block content %}
{% endblock %}


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
{% block js %} {% endblock %}


<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->


<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
-->
<br>

</body>


<footer class="spad pb-0">
    <div class="footer-bottom">
        <div class="footer-warp">
            <ul class="footer-menu">
                <li><a href="{% url 'terms_conditions' %}">Terms & Conditions</a></li>
                <li><a href="{% url 'privacy' %}">Privacy</a></li>
            </ul>
            <div class="">Copyright &copy; a2z Learning Store
                <script>document.write(new Date().getFullYear());</script>
                All rights reserved.
            </div>
        </div>
    </div>

</footer>
<!--====== Javascripts & Jquery ======-->
<script src="{% static 'webuni/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'webuni/js/bootstrap.min.js' %}"></script>
<script src="{% static 'webuni/js/mixitup.min.js' %}"></script>
<script src="{% static 'webuni/js/circle-progress.min.js' %}"></script>
<script src="{% static 'webuni/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'webuni/js/main.js' %}"></script>
<script src="{% static 'webuni/js/freelancer.js' %}"></script>
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
    AOS.init();





</script>

</html>

347project/347project/learningproject/a2zStore/templates/a2zStore/checkout.html
{% extends 'users/base.html' %}

{% block title %}Check Out{% endblock %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
        </div>
        <a href="{% url 'store' %}">< Back</a>
    </div>
</div>
<div class="container">
    <div class="text-center">
        <h2>A2Z Store Express Checkout - Review Your Cart Items</h2>
        <hr>
        <br>
        <div class="my-4">
            <ul class="list-group" id="items">
            </ul>
            <nav aria-label="breadcrumb">
                  <ol class="breadcrumb mt-3">
                    <li class="breadcrumb-item active" aria-current="page">Your Cart Total Is <b>TK.<span id="totalPrice"> </span> </b>  Enter your details below & place your order. Thanks for using A2Z Store!</li>
                  </ol>
                <b> <p style="font-size:30px;color:red;">"We will contact you via email for payment"</p></b>

            </nav>
        </div>
    </div>
    <div class="col my-4">
        <h2>Enter Address & Other Details:</h2>
        <form method="post" action="/a2zStore/checkout/"> {% csrf_token %}
            <input type="hidden" name="itemsJson" id="itemsJson">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name ="name" placeholder="Name">
                </div>
                <div class="form-group col-md-6">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name= "email" placeholder="Email">
                </div>
            </div>
            <div class="form-group">
                <label for="address1">Address 1</label>
                <input type="text" class="form-control" id="address1" name="address1" placeholder="Permanent Address">
            </div>
            <div class="form-group">
                <label for="address2">Address 2</label>
                <input type="text" class="form-control" id="address2" name="address2" placeholder="Delivery Address">
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="city">City</label>
                    <input type="text" class="form-control" id="city" name="city">
                </div>
                <div class="form-group col-md-4">
                    <label for="state">State</label>
                    <input type="text" class="form-control" id="state" name="state" placeholder="Enter State">
                </div>
                <div class="form-group col-md-2">
                    <label for="zip_code">Zip</label>
                    <input type="text" class="form-control" id="zip_code" name="zip_code">
                </div>
            </div>
            <div class="form-group">
                <label for="phone">Phone Number</label>
                <input type="text" class="form-control" id="phone" name="phone">
            </div>
            <button type="submit" class="btn btn-primary">Place Order</button>
        </form>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
if (localStorage.getItem('cart') == null) {
    var cart = {};
} else {
    cart = JSON.parse(localStorage.getItem('cart'));
}
console.log(cart);
var sum=0;
var totalPrice = 0;
if ($.isEmptyObject(cart)) {
    //if object is empty
    mystr = `<p>Your cart is empty, please add some items to your cart before checking out!</p>`
    $('#items').append(mystr);
} else {
    for (item in cart) {
        let name = cart[item][1];
        let qty = cart[item][0];
        let itemPrice = cart[item][2];
        sum = sum + qty;
        totalPrice = totalPrice + qty * itemPrice;
        mystr = `<li class="list-group-item d-flex justify-content-between align-items-center">
                    ${name}
                    <span class="badge badge-primary badge-pill">${qty}</span>
                </li>`
        $('#items').append(mystr);
    }
}

document.getElementById('cart').innerHTML = sum;
document.getElementById('totalPrice').innerHTML = totalPrice;
$('#itemsJson').val(JSON.stringify(cart));
{% if thank %}
alert("Thanks for ordering with us. Your order id is {{id}}. Use it to track your order using our order tracker.")
localStorage.clear();
document.location="/a2zStore/";
{%endif%}
</script>
{% endblock %}

347project/347project/learningproject/a2zStore/templates/a2zStore/index.html
{% extends 'a2zStore/basic.html' %}
{% block css %}
      .col-md-3
      {
      display: inline-block;
      margin-left:-4px;
      }
      .carousel-indicators .active{
      background-color: blue;
      }

      .col-md-3 img{
      width:227px;
      height:242px;
      }

      body .carousel-indicator li{
      background-color: blue;
      }
      body .carousel-indicators{
      bottom:0;
      }

      body .carousel-control-prev-icon,
      body .carousel-control-next-icon{
      background-color: blue;
      }
      .carousel-control-prev,
      .carousel-control-next{
      top: auto;
      bottom: auto;
      padding-top: 220px;
      }
      body .no-padding{
      padding-left = 0,
      padding-right = 0;
      }
{% endblock %}
{% block content %}
{% load static %}
<div class="container">
    <!--slide show starts -->
    {% for product, range, nSlide in allProds %}
    <h1 class = "my-4"> {{product.0.category}}</h1>
    <div class= "row d-flex justify-content-center">
     <div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride ="carousel">
          <ul class = "carousel-indicators">
            <li data-target = "#demo{{forloop.counter}}" data-slide-to = "0" class = "active d-flex justify-content-center"></li>

              {% for i in range %}
            <li data-target = "#demo{{forloop.parentloop.counter}}" data-slide-to = "{{i}}" ></li>
            {% endfor %}
          </ul>

          <div class="container carousel-inner no-padding ">
            <div class = "carousel-item active ">

                {% for i in product %}
              <div class = "col-xs-3 col-sm-3 col-md-3 ">
                <div class="card o-hidden border-0 shadow-lg align-items-center" style="width: 16rem;">
                    <img class="card-img-top" src='/media/{{i.image}}' alt="Card image cap">
                    <div class="card-body text-center">
                      <h6 class="card-title" id = "namepr{{i.id}}">{{i.product_name}}</h6>

                        <h7 class="card-title" ><small>Price : <span id="pricepr{{i.id}}">{{i.price}}</span></small></h7>
                        <br>
                      <span id="divpr{{i.id}}" class = "divpr">

                      <button id = "pr{{i.id}}" class="btn btn-primary cart">Add</button>
                      </span>
                      <a href="/a2zStore/products/{{i.id}}"><button id = "qv{{i.id}}" class="btn btn-primary cart">View</button></a>
                    </div>
                </div>
              </div>
                {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
                </div><div class = "carousel-item">
                {% endif %}

                {% endfor %}

              </div>
           </div>
       </div>
            <!-- left right controls for slide show -->
            <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
              <span class ="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
                  <span class ="carousel-control-next-icon"></span>
            </a>
    </div>
        {% endfor %}
    </div>
        {% endblock %}

{% block js %}

<!-- javascript from here -->
<script>
// Find out the cart items from localStorage
if (localStorage.getItem('cart') == null) {
    var cart = {};
} else {
    cart = JSON.parse(localStorage.getItem('cart'));
    updateCart(cart);
}
$('.divpr').on('click', 'button.cart', function() {
    var idstr = this.id.toString();
    if (cart[idstr] != undefined) {
        qty = cart[idstr][0] + 1;

    } else {
        qty = 1;
        name = document.getElementById('name'+idstr).innerHTML;
        price = document.getElementById('price'+idstr).innerHTML;
        cart[idstr] = [qty, name, parseInt(price)];

    }
    updateCart(cart);
});
//Add Popover to cart
$('#popcart').popover();
updatePopover(cart);

function updatePopover(cart) {
    console.log('We are inside updatePopover');
    var popStr = "";
    popStr = popStr + "<h5> Cart for your items in my shopping cart </h5><div class='mx-2 my-2'>";
    var i = 1;
    for (var item in cart) {
        popStr = popStr + "<b>" + i + "</b>. ";
        popStr = popStr + document.getElementById('name' + item).innerHTML.slice(0, 19) + "... Qty: " + cart[item][0] + '<br>';
        i = i + 1;
    }
    popStr = popStr + "</div> <a href='/a2zStore/checkout'><button class='btn btn-primary' id ='checkout'>Checkout</button></a> <button class='btn btn-primary' onclick='clearCart()' id ='clearCart'>Clear Cart</button>     "
    console.log(popStr);
    document.getElementById('popcart').setAttribute('data-content', popStr);
    $('#popcart').popover('show');
}

function clearCart() {
    cart = JSON.parse(localStorage.getItem('cart'));
    for (var item in cart) {
        document.getElementById('div' + item).innerHTML = '<button id="' + item + '" class="btn btn-primary cart">Add</button>'
    }
    localStorage.clear();
    cart = {};
    updateCart(cart);
}

function updateCart(cart) {
    var sum = 0;
    for (var item in cart) {
        sum = sum + cart[item][0];
        document.getElementById('div' + item).innerHTML = "<button id='minus" + item + "' class='btn btn-primary minus'>-</button> <span id='val" + item + "''>" + cart[item][0] + "</span> <button id='plus" + item + "' class='btn btn-primary plus'> + </button>";
    }
    localStorage.setItem('cart', JSON.stringify(cart));
    document.getElementById('cart').innerHTML = sum;
    console.log(cart);
    updatePopover(cart);
}
// If plus or minus button is clicked, change the cart as well as the display value
$('.divpr').on("click", "button.minus", function() {
    a = this.id.slice(7, );
    cart['pr' + a][0] = cart['pr' + a][0] - 1;
    cart['pr' + a][0] = Math.max(0, cart['pr' + a][0]);
    document.getElementById('valpr' + a).innerHTML = cart['pr' + a][0];
    updateCart(cart);
});
$('.divpr').on("click", "button.plus", function() {
    a = this.id.slice(6, );
    cart['pr' + a][0] = cart['pr' + a][0] + 1;
    document.getElementById('valpr' + a).innerHTML = cart['pr' + a][0];
    updateCart(cart);
});
</script>
{% endblock %}